name: Delete

on:
  pull_request:
    types: [closed]

jobs:
  delete_reports:
    name: Delete Reports
    runs-on: ubuntu-latest
    env:
      # Contains all reports for deleted branch
      BRANCH_REPORTS_DIR: reports/${{ github.event.pull_request.head.ref }}
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: fregante/setup-git-user@v2
      - name: Check for workflow reports
        run: |
          if [ -z "$(ls -A $BRANCH_REPORTS_DIR)" ]; then
            echo "BRANCH_REPORTS_EXIST="false"" >> $GITHUB_ENV
            echo "::notice $BRANCH_REPORTS_EXIST"
          else
            echo "BRANCH_REPORTS_EXIST="true"" >> $GITHUB_ENV
            echo "::notice $BRANCH_REPORTS_EXIST"
          fi
      - name: Delete reports from repo for branch
        if: ${{ env.BRANCH_REPORTS_EXIST == 'true' }}
        timeout-minutes: 3
        run: |
          cd $BRANCH_REPORTS_DIR/..

          git rm -r rm -rf ${{ github.event.pull_request.head.ref }}
          git add .
          git commit -c  user.name "github-actions[bot]" user.email "41898282+github-actions[bot]@users.noreply.github.com" -m "workflow: remove all reports for branch ${{ github.event.pull_request.head.ref  }}"

          while true; do
            git push
            if [ $? -eq 0 ]; then
              echo "Successfully pushed HTML reports to repo."
              exit 0
            fi
          done
