name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1
  merge-reports:
    needs: [playwright-tests]
    if: ${{ always() && (needs.playwright-tests.result == 'success' || needs.playwright-tests.result == 'failure') }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge latest into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload latest HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14

  publish_report:
    name: Publish HTML Report
    if: "success() || needs.test.result == 'failure'"
    needs: [merge-reports]
    runs-on: ubuntu-latest
    continue-on-error: true

    env:
      HTML_REPORT_URL_PATH_MAIN: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
      HTML_REPORT_URL_PATH: reports/${{ github.head_ref }}/${{ github.run_id }}/${{ github.run_attempt }}

    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download zipped HTML report
        uses: actions/download-artifact@v4
        if: github.ref != 'refs/heads/main'
        with:
          name: playwright-report
          path: ${{ env.HTML_REPORT_URL_PATH }}

      - name: Download zipped HTML report for main branch
        uses: actions/download-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: playwright-report
          path: ${{ env.HTML_REPORT_URL_PATH_MAIN }}

      - name: Push HTML Report
        timeout-minutes: 3
        run: |
          git add .
          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"

          while true; do
            git pull --rebase
            if [ $? -ne 0 ]; then
              echo "Failed to rebase. Please review manually."
              exit 1
            fi

            git push
            if [ $? -eq 0 ]; then
              echo "Successfully pushed HTML report to repo."
              exit 0
            fi
          done

      - name: Set FULL_HTML_REPORT_URL
        if: github.ref != 'refs/heads/main'
        run: echo "FULL_HTML_REPORT_URL=https://nav-2d.github.io/upload-pw-reports/$HTML_REPORT_URL_PATH" >> $GITHUB_ENV

      - name: Output Report URL as Worfklow Annotation
        if: github.ref != 'refs/heads/main'
        run: |
          FULL_HTML_REPORT_URL=https://nav-2d.github.io/upload-pw-reports/$HTML_REPORT_URL_PATH
          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"

      - uses: actions/github-script@v7
        if: github.ref != 'refs/heads/main'
        with:
          script: |
            const fullReportUrl = process.env.FULL_HTML_REPORT_URL;
             const emoji = needs.playwright-tests.result == 'success' ? ':x:' : ':white_check_mark:';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${emoji} Published Playwright Test Report: [View Report](${fullReportUrl})`
            })

      - name: Output Report URL as Worfklow Annotation
        if: github.ref == 'refs/heads/main'
        run: |
          FULL_HTML_REPORT_URL=https://nav-2d.github.io/upload-pw-reports/$HTML_REPORT_URL_PATH_MAIN
          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
